apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-service-nodeport 
spec: 
  type: NodePort
  ports: 
    - port: 8000
      targetPort: 80 
      protocol: TCP 
      nodePort: 30001
  selector: 
    name: nginx
