apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginx
  labels:
    name: mynginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: mynginx
        image: nginx
        ports:
        - containerPort: 80
